export const TAGS = [
  { label: "NIN verification Nigeria", size: 24 }, { label: "BVN verification", size: 23 },
  { label: "Nigerian identity check", size: 22 }, { label: "passport verification Nigeria", size: 21 },
  { label: "driver's licence verification Nigeria", size: 20 }, { label: "voter card verification", size: 19 },
  { label: "CAC verification", size: 18 }, { label: "business verification Nigeria", size: 20 },
  { label: "KYC Nigeria", size: 24 }, { label: "AML compliance Nigeria", size: 19 },
  { label: "fraud prevention Nigeria", size: 23 }, { label: "eKYC API Nigeria", size: 22 },
  { label: "identity verification API", size: 21 }, { label: "document verification Nigeria", size: 19 },
  { label: "background check Nigeria", size: 18 }, { label: "address verification Nigeria", size: 17 },
  { label: "bank account verification Nigeria", size: 20 }, { label: "fintech verification Nigeria", size: 22 },
  { label: "compliance solutions Nigeria", size: 19 }, { label: "pre-employment screening Nigeria", size: 18 },
  { label: "real-time identity verification", size: 24 }, { label: "automated KYC", size: 16 },
  { label: "ID verification API", size: 20 }, { label: "secure identity verification", size: 19 },
  { label: "Nigerian KYC solution", size: 21 }, { label: "digital identity Nigeria", size: 20 },
  { label: "identity fraud prevention Nigeria", size: 18 }, { label: "risk assessment Nigeria", size: 22 },
  { label: "regulatory compliance Nigeria", size: 17 }, { label: "NIMC verification", size: 19 },
  { label: "INEC voter check", size: 18 }, { label: "CBN compliance", size: 16 },
  { label: "instant verification Nigeria", size: 23 }, { label: "KYB verification Nigeria", size: 15 },
  { label: "white-label verification Nigeria", size: 16 }, { label: "PVC verification", size: 17 },
  { label: "phone number verification Nigeria", size: 18 }, { label: "employment verification Nigeria", size: 19 },
  { label: "ID Me Naija", size: 24 }, { label: "idmenaija", size: 16 },
];